---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: Crie um novo servidor SQL PostgreSQL na fábrica de cargas de trabalho do BlueXP  para bancos de dados. 
---
= Crie um servidor PostgreSQL na fábrica de carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Criar um novo servidor PostgreSQL, ou host de banco de dados, na fábrica de carga de trabalho do BlueXP  para bancos de dados requer uma implantação do sistema de arquivos FSX for ONTAP e recursos para ative Directory.

.Sobre esta tarefa
Você precisará de credenciais de conta da AWS e permissões _Automate_.

Antes de começar, saiba mais sobre os tipos de implantação de armazenamento disponíveis para a configuração de host de banco de dados, implantação do ative Directory, modos de operação de fábrica de carga de trabalho e os requisitos para concluir essa operação.

FSX para implantações de sistema de arquivos ONTAP:: Criar um novo servidor PostgreSQL requer um sistema de arquivos FSX for ONTAP como o back-end de armazenamento. Você pode usar um sistema de arquivos FSX for ONTAP existente ou criar um novo sistema de arquivos. Se você selecionar um sistema de arquivos FSX for ONTAP existente como back-end de armazenamento do servidor de banco de dados, nós criamos uma nova VM de armazenamento para as cargas de trabalho do PostgreSQL.
+
--
O FSX para sistemas de arquivos ONTAP suporta implantações _standalone_ para PostgreSQL. A fábrica do Workload cria um sistema de arquivos FSX for ONTAP com zona de disponibilidade única, além de volumes e LUNs separados para dados, log e arquivos tempdb.

--
Modos de operação de fábrica da carga de trabalho:: A fábrica de carga de trabalho oferece três modos operacionais, dependendo do quão confortável você está com permitir que a fábrica de carga de trabalho gerencie seus recursos da AWS.
+
--
*_Basic_ mode*: Neste modo de operação, você não precisa associar nenhuma credencial de conta da AWS na fábrica de carga de trabalho. Você pode copiar ou baixar um modelo YAML parcialmente preenchido da caixa de códigos para ser concluído fora da fábrica de carga de trabalho.

*_Read_ mode*: Neste modo de operação, você fornece credenciais de conta da AWS com permissões de leitura que permitem concluir o formulário _Quick Create_ ou _Advanced Create_ e depois copiá-lo ou baixá-lo. Você também pode redirecionar para o CloudFormation da fábrica de carga de trabalho com os detalhes do formulário preenchido. E você será capaz de gerenciar o servidor de banco de dados implantado na fábrica de carga de trabalho.

*_Automate_ mode*: Neste modo de operação, você fornece credenciais de conta da AWS com permissões de automação, que permitem criar e gerenciar recursos da AWS na fábrica de cargas de trabalho.

--


.Antes de começar
Certifique-se de que você tem os seguintes pré-requisitos antes de criar um novo host de banco de dados.

Credenciais e permissões:: Você precisa link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenciais de conta da AWS e permissões de modo de automação"^]criar um novo host de banco de dados na fábrica de workloads.




== Crie um servidor de banco de dados

Você pode usar o modo de implantação _Advanced Create_ para concluir essa tarefa na fábrica de carga de trabalho com permissões do modo _Automate_. Você também pode usar as seguintes ferramentas disponíveis no Codebox: API REST, AWS CLI e AWS CloudFormation. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Saiba como usar o Codebox para automação"^].

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *Deploy database host* e, em seguida, selecione *PostgreSQL* no menu suspenso.
. Selecione *Advanced Create*.
. Para *modelo de implantação*, *instância independente* é o padrão.
. Em *configurações da AWS*, forneça o seguinte:
+
.. *Credenciais da AWS*: Selecione credenciais da AWS com permissões de automação para implantar o novo host de banco de dados.
+
As credenciais da AWS com permissões _Automate_ permitem que a carga de trabalho implante e gerencie o novo host de banco de dados a partir da sua conta da AWS dentro da fábrica de carga de trabalho.

+
As credenciais da AWS com permissões _read_ permitem que a fábrica da carga de trabalho gere um modelo do CloudFormation para você usar no console do AWS CloudFormation.

+
Se você não tiver credenciais da AWS associadas à fábrica de carga de trabalho e quiser criar o novo servidor na fábrica de carga de trabalho, siga a *opção 1* para ir para a página credenciais. Adicione manualmente as credenciais e permissões necessárias para o modo _Automate_ para cargas de trabalho de banco de dados.

+
Se você quiser preencher o formulário criar novo servidor na fábrica de carga de trabalho para que você possa baixar um modelo de arquivo YAML completo para implantação no AWS CloudFormation, siga a *opção 2* para garantir que você tenha as permissões necessárias para criar o novo servidor no AWS CloudFormation. Adicione manualmente as credenciais e permissões necessárias para o modo _read_ para cargas de trabalho de banco de dados.

+
Opcionalmente, você pode baixar um modelo de arquivo YAML parcialmente concluído da caixa de código para criar a pilha fora da fábrica de carga de trabalho sem credenciais ou permissões. Selecione *CloudFormation* no menu suspenso na caixa de código para baixar o arquivo YAML.

.. *Região e VPC*: Selecione uma região e uma rede VPC.
+
Certifique-se de que os grupos de segurança para um endpoint de interface existente permitem o acesso ao protocolo HTTPS (443) às sub-redes selecionadas.

+
Endpoints de interface do AWS Service (SQS, FSX, EC2, CloudWatch, Cloud Formation, SSM) e endpoint de gateway S3 são criados durante a implantação se não forem encontrados.

+
Os atributos DNS da VPC `EnableDnsSupport` e `EnableDnsHostnames` são modificados para habilitar a resolução de endereços de endpoint se ainda não estiverem definidos como `true`.

.. *Zonas de disponibilidade*: Selecione zonas de disponibilidade e sub-redes.
+
Para implantações de uma única instância::
+
--
... No campo *Configuração de cluster - nó 1*, selecione uma zona de disponibilidade no menu suspenso *zona de disponibilidade* e uma sub-rede no menu suspenso *Subnet*.


--


.. *Grupo de segurança*: Selecione um grupo de segurança existente ou crie um novo grupo de segurança.
+
Dois grupos de segurança são anexados aos nós SQL (instâncias EC2) durante a implantação do novo servidor.

+
... Um grupo de segurança de carga de trabalho é criado para permitir portas e protocolos necessários para o PostgreSQL.
... Para um sistema de arquivos FSX for ONTAP existente, o grupo de segurança associado a ele é adicionado automaticamente ao nó PostgreSQL, que permite a comunicação com o sistema de arquivos. Quando um novo sistema FSX for ONTAP é criado, um novo grupo de segurança é criado para o sistema de arquivos FSX for ONTAP e o mesmo grupo de segurança também é anexado ao nó SQL.




. Em *Definições da aplicação*, forneça o seguinte:
+
.. Selecione o *sistema operacional* no menu suspenso.
.. Selecione a *versão PostgreSQL* no menu suspenso.
.. *Nome do servidor do banco de dados*: Insira o nome do cluster do banco de dados.
.. *Credenciais da base de dados*: Introduza um nome de utilizador e uma palavra-passe para uma nova conta de serviço ou utilize credenciais de conta de serviço existentes no ative Directory.


. Em *conetividade*, selecione um par de chaves para se conetar com segurança à sua instância.
. Em *Configurações de infra-estrutura*, forneça o seguinte:
+
.. *Tipo de instância de banco de dados*: Selecione o tipo de instância de banco de dados no menu suspenso.
.. *FSX para sistema ONTAP*: Crie um novo sistema de arquivos FSX for ONTAP ou use um sistema de arquivos FSX for ONTAP existente.
+
... *Criar novo FSX para ONTAP*: Insira o nome de usuário e a senha.
+
Um novo sistema de arquivos FSX for ONTAP pode adicionar 30 minutos ou mais de tempo de instalação.

... *Selecione um FSX for ONTAP* existente: Selecione o nome FSX for ONTAP no menu suspenso e insira um nome de usuário e senha para o sistema de arquivos.
+
Para sistemas de arquivos FSX para ONTAP existentes, verifique o seguinte:

+
**** O grupo de roteamento anexado ao FSX for ONTAP permite que as rotas para as sub-redes sejam usadas para implantação.
**** O grupo de segurança permite o tráfego das sub-redes usadas para implantação, especificamente as portas TCP HTTPS (443) e iSCSI (3260).




.. *Política de instantâneos*: Ativada por padrão. Os snapshots são feitos diariamente e têm um período de retenção de 7 dias.
+
Os snapshots são atribuídos a volumes criados para cargas de trabalho PostgreSQL.

.. *Tamanho da unidade de dados*: Insira a capacidade da unidade de dados e selecione a unidade de capacidade.
.. *IOPS provisionados*: Selecione *Automático* ou *aprovisionado pelo usuário*. Se você selecionar *User-provisioned*, digite o valor IOPS.
.. *Capacidade de throughput*: Selecione a capacidade de throughput no menu suspenso.
+
Em certas regiões, você pode selecionar capacidade de taxa de transferência de 4 Gbps. Para provisionar 4 Gbps de capacidade de taxa de transferência, o sistema de arquivos FSX for ONTAP deve ser configurado com um mínimo de 5.120 GiB de capacidade de armazenamento SSD e 160.000 IOPS SSD.

.. *Criptografia*: Selecione uma chave da sua conta ou uma chave de outra conta. Você deve inserir a chave de criptografia ARN de outra conta.
+
As chaves de criptografia personalizadas do FSX for ONTAP não são listadas com base na aplicabilidade do serviço. Selecione uma chave de criptografia FSX apropriada. As chaves de criptografia não FSX causarão falha na criação do servidor.

+
As chaves gerenciadas pela AWS são filtradas com base na aplicabilidade do serviço.

.. *Tags*: Opcionalmente, você pode adicionar até 40 tags.
.. *Simple Notification Service*: Opcionalmente, você pode ativar o Simple Notification Service (SNS) para esta configuração selecionando um tópico SNS para o Microsoft SQL Server no menu suspenso.
+
... Ative o Serviço de notificação simples.
... Selecione um ARN no menu pendente.


.. *Monitoramento do CloudWatch*: Opcionalmente, você pode ativar o monitoramento do CloudWatch.
+
Recomendamos ativar o CloudWatch para depuração em caso de falha. Os eventos que aparecem no console do AWS CloudFormation são de alto nível e não especificam a causa raiz. Todos os logs detalhados são salvos na `C:\cfn\logs` pasta nas instâncias EC2.

+
No CloudWatch, um grupo de log é criado com o nome da pilha. Um fluxo de log para cada nó de validação e nó SQL aparece sob o grupo de log. O CloudWatch mostra o progresso do script e fornece informações para ajudá-lo a entender se e quando a implantação falhar.

.. *Reversão de recursos*: Este recurso não é suportado no momento.


. Resumo
+
.. *Custo estimado*: Fornece uma estimativa das cobranças que você pode incorrer se você implantou os recursos mostrados.


. Clique em *Create* para implantar o novo host de banco de dados.
+
Alternativamente, você pode salvar a configuração.



.O que vem a seguir
Você pode configurar manualmente usuários, acesso remoto e bancos de dados no servidor PostgreSQL implantado.
