---
sidebar: sidebar 
permalink: deregister-instance.html 
keywords: Microsoft SQL Server instance, PostgreSQL server instance, Oracle database, deregister instance, unregister instance, remove instance 
summary: Cancele o registro de um recurso se não quiser mais implantar ou monitorar recursos do console do Workload Factory. 
---
= Cancelar o registro de um recurso no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cancele o registro de um recurso, como uma instância do Microsoft SQL Server ou um banco de dados Oracle, se não quiser mais implantar ou monitorar recursos do console do NetApp Workload Factory. O cancelamento do registro de recursos também remove a quantidade de capacidade de armazenamento do FSx para ONTAP usada pela instância.

Você pode registrar o recurso novamente.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. No menu Bancos de dados, selecione *Inventário*.
. No Inventário, selecione o tipo de mecanismo: *Microsoft SQL Server*, *Oracle* ou *PostgreSQL*.
. Localize o recurso que você deseja cancelar o registro, selecione o menu de ação e, em seguida, selecione *Cancelar registro*.

