---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado. 
---
= Limitações conhecidas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado.



== Suporte à versão de imagem AMI

Mostramos apenas até quatro versões recentes ou revisões de imagens AMI para cada versão SQL. Não permitimos a instalação a partir de uma imagem AMI mais antiga do que as quatro versões mais recentes.



== AMI personalizado

A implementação com uma AMI personalizada assume que a Mídia de instalação está presente na imagem. Isso é necessário para a configuração do FCI pelos seguintes motivos:

* Para desinstalar e reconfigurar para formar o cluster FCI
* Ao selecionar uma ordenação diferente do conjunto de ordenação na imagem para implementação autónoma


Como parte da implantação, o Workload Factory não instala uma AMI personalizada com várias instâncias do Microsoft SQL Server. Somente a instância padrão do Microsoft SQL Server é selecionada e configurada como parte da implantação.



== Reverter e tentar novamente para implantações com falha

A reversão e a tentativa de implantação com falha não são suportadas no Workload Factory. Você pode reverter ou tentar novamente uma pilha com falha no console do CloudFormation na AWS.



== Reversão de recursos do ative Directory e DNS

Os seguintes recursos DNS não são removidos do ative Directory e DNS quando você reverte um teste ou falha na implantação do console do CloudFormation na AWS:

* Cada nó da implantação SQL para seu endereço IP de gerenciamento
* Nome do cluster do Windows para os endereços IP secundários reservados de instâncias EC2 em casos de FCI
* Nome SQL FCI para os dois endereços IP reservados de ambas as instâncias EC2 no FCI


Você precisará limpá-los manualmente ou esperar que o domínio limpe as entradas obsoletas.



== Suporte à configuração de grupos de disponibilidade sempre ativa

O gerenciamento de configurações de grupos sempre ativos não é compatível com o Workload Factory.



== Grupos de segurança do ative Directory gerenciados pelo usuário

Se você selecionar "ative Directory gerenciado pelo usuário" durante a implantação do Microsoft SQL Server no Workload Factory, você deverá fornecer um grupo de segurança que permita o tráfego entre as instâncias EC2 para o serviço de diretório para implantação. O Workload Factory não anexa automaticamente o grupo de segurança para o ative Directory gerenciado pelo usuário, como acontece com o AWS Managed Microsoft AD.



== Chaves de criptografia personalizadas

As chaves de criptografia personalizadas para o FSX for ONTAP não estão listadas com base na aplicabilidade do serviço. Você deve escolher a chave apropriada. As chaves gerenciadas da AWS são filtradas com base na aplicabilidade ao serviço.



== Modelo do CloudFormation

Um modelo do CloudFormation gerado pelo Codebox baixado ou copiado (arquivo YAML) tem um período de retenção limitado de sete dias.



== Suporte sandbox

O número máximo de clones sandbox que podem ser criados a partir de um servidor de banco de dados é 90.



== Detecção e gerenciamento do Microsoft SQL Server

A deteção do Microsoft SQL Server não é salva. Cada vez que você acessa bancos de dados no Workload Factory, a deteção do Microsoft SQL Server é executada novamente para identificar instalações SQL na região.



== Explore as poupanças

Na guia Inventário, o custo estimado mostrado para cada instância do Microsoft SQL é calculado no nível do sistema de arquivos FSX for ONTAP e não para volumes que hospedam a instância SQL.



== Vários sistemas de arquivos FSX para ONTAP

O Workload Factory não suporta a criação ou a gravação de configurações para o Microsoft SQL Server com vários sistemas de arquivos FSX for ONTAP. Apenas uma implantação de configuração do sistema de arquivos FSX for ONTAP é suportada.



== Disponibilidade regional para implantação do Microsoft SQL Server em uma rede privada com o Terraform

A implantação do Microsoft SQL Server em uma rede privada sem conetividade de saída usando o Terraform só é suportada na região US-East-1 (N. Virginia).
