---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: O NetApp Workload Factory for Databases é um serviço completo de implantação e manutenção de banco de dados com práticas recomendadas integradas para otimização, clonagem fina automática e recursos de monitoramento e resolução. 
---
= Saiba mais sobre o NetApp Workload Factory para bancos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory for Databases é um serviço completo de implantação e manutenção de banco de dados com práticas recomendadas integradas para otimização, clonagem fina automática e recursos de monitoramento e resolução.



== O que é o NetApp Workload Factory para bancos de dados?

O NetApp Workload Factory for Databases detecta, avalia, planeja, provisiona e move dados do Microsoft SQL Server para o Amazon FSx for NetApp ONTAP (FSx for ONTAP) otimizadas para atender às suas expectativas de desempenho e custo, ao mesmo tempo em que aderem às melhores práticas do setor.  Ao longo do ciclo de vida, o NetApp Workload Factory for Databases oferece otimização e gerenciamento contínuos para bancos de dados no FSx para ONTAP.

Para obter mais informações sobre o Workload Factory, consulte olink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Visão geral da Workload Factory"^] .



== Benefícios do Workload Factory para bancos de dados autogerenciados

O Workload Factory oferece as seguintes práticas recomendadas e automação benéficas para bancos de dados autogerenciados.



=== Práticas recomendadas

* Conhecimento integrado dos servidores AWS Cloud, Microsoft Windows e SQL e NetApp ONTAP para implantações de servidor SQL em instâncias EC2.
* Implantação otimizada do custo total de propriedade.
* Automação de implantação completa que segue as práticas recomendadas da AWS, Microsoft e ONTAP.
* O modo de implantação de _criação rápida_ ajuda a evitar possíveis armadilhas com configuração manual.




=== Automação com Workload Factory Codebox

O Workload Factory apresenta automação integrada com o _Codebox_.  O Codebox oferece os seguintes benefícios de automação:

* *Geração de snippets de código*: Snippets de infraestrutura como código (IAC) são gerados durante a criação de recursos, permitindo uma integração perfeita com fluxos de trabalho de orquestração existentes.
* *Copiloto de infraestrutura como código*: o Codebox é um copiloto de infraestrutura como código (IaC) que ajuda desenvolvedores e DevOps a gerar código para executar qualquer operação suportada pelo Workload Factory.
* *Visualizador de código e catálogo de automação*: O Codebox fornece um visualizador de código para análise rápida da automação e um catálogo de automação para rápida reutilização futura.




=== Recursos do Workload Factory para bancos de dados

O Workload Factory for Databases oferece os seguintes recursos:

* * Implantações simples e rápidas*: Simplifique e simplifique sua experiência de provisionamento selecionando respostas para perguntas de especificação e eliminando o tempo normalmente necessário para investigar como provisionar e configurar seu Microsoft SQL Server na AWS.
* *Orquestração automatizada*: disponível por meio do console do Workload Factory com modos de criação de implantação _Rápido_ e _Avançado_, o Chatbot e o AWS CloudFormation por meio do Codebox.
* *Recursos incorporados*: Utilize as melhores práticas do NetApp, Microsoft e Amazon e seleções de recursos da AWS incorporadas à configuração de implantação.
* *Estimativa de custo*: Avalie possíveis economias de custo com a calculadora de economia que estima e detalha os custos de armazenamento, computação, licenciamento SQL, snapshot e clone detalhados para implantações existentes do Microsoft SQL Server com o Elastic Block Store e o FSX for Windows File Server em comparação com o FSX for ONTAP.
* *Modelos de automação reutilizáveis*: crie, reutilize e personalize modelos do CloudFormation a partir do Workload Factory Codebox para futuras implantações do Microsoft SQL Server em vários ambientes.
* *Descoberta e provisionamento de recursos da AWS*: Detecte automaticamente os servidores Microsoft SQL no FSX for ONTAP, FSX for Windows File Servers e Elastic Block Store implantados a partir de sua conta da AWS. O Inventário de bancos de dados serve como ponto de lançamento para explorar oportunidades de economia de custos para servidores em outros sistemas de armazenamento da AWS ou uma ferramenta de gerenciamento para servidores e instâncias baseados no FSX for ONTAP.
* * Criação de sandbox*: Crie um ambiente de banco de dados isolado sob demanda que pode ser usado para teste, integração, diagnóstico e treinamento, sem afetar os dados de produção.
* * Criação de banco de dados*: Crie um banco de dados de usuários para seus servidores Microsoft SQL existentes com os modos _Quick_ ou _Advanced_ Create para configurar o agrupamento de banco de dados, nomes de arquivos e tamanhos. A configuração de armazenamento está incluída.
* *Monitoramento de trabalho*: Monitore e acompanhe o progresso da execução do trabalho do banco de dados e diagnostique e solucione problemas no caso de ocorrer alguma falha.
* * Otimização contínua*: Verifica continuamente o estado do Microsoft SQL Server offline, fornecendo-lhe um relatório abrangente de insights, oportunidades e recomendações para ajudá-lo a alcançar a excelência operacional.




== Benefícios do Amazon FSX for ONTAP para bancos de dados autogeridos

* *Durabilidade, disponibilidade e confiabilidade*: O FSX for ONTAP oferece vários recursos que aumentam a durabilidade e a disponibilidade de bancos de dados autogeridos hospedados no FSX for ONTAP, como alta disponibilidade com suporte a implantações de zonas de disponibilidade única e múltipla, snapshots com reconhecimento de aplicativos, recuperação de desastres aprimorada usando replicação e backup eficiente.
* *Desempenho e escalabilidade*: O FSX for ONTAP oferece otimização de desempenho com alta taxa de transferência, baixa latência, conexões de rede de alta velocidade e escalabilidade com vários sistemas de arquivos para dimensionar o desempenho agregado necessário para uma carga de trabalho.
* *Gerenciamento e eficiência de dados*: O FSX for ONTAP oferece vários recursos que aprimoram o gerenciamento e a eficiência de dados, como thin clones com uso eficiente de espaço, thin Provisioning, compactação e deduplicação e disposição em camadas de dados acessados com pouca frequência no pool de capacidade.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Saiba mais sobre o FSx para ONTAP para Workload Factory"^] .



=== Modos operacionais na Workload Factory

Três modos operacionais diferentes — _básico_, _somente leitura_ e _leitura/gravação_ — oferecem opções flexíveis para implantação dentro e fora do Workload Factory. Obtenha valor imediato em confiança zero no modo _básico_ com trechos de código para uso fora do Workload Factory. Obtenha valor incremental com confiança incremental nos modos _somente leitura_ e _leitura/gravação_.

Saiba mais sobre link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["modos operacionais na Workload Factory"^] .



== Ferramentas para usar o NetApp Workload Factory

Você pode usar o NetApp Workload Factory com as seguintes ferramentas:

* *Console do Workload Factory*: O console do Workload Factory fornece uma visão visual e holística de seus aplicativos e projetos.
* * NetApp Console*: O NetApp Console oferece uma experiência de interface híbrida para que você possa usar o Workload Factory junto com outros serviços de dados do NetApp .
* *Pergunte-me*: use o assistente de IA Ask me para fazer perguntas e saber mais sobre o Workload Factory sem sair do console do Workload Factory. Acesse Pergunte-me no menu de ajuda do Workload Factory.
* *CloudShell CLI*: O Workload Factory inclui um CloudShell CLI para gerenciar e operar ambientes AWS e NetApp em todas as contas a partir de um único CLI baseado em navegador. Acesse o CloudShell na barra superior do console do Workload Factory.
* *API REST*: Use as APIs REST do Workload Factory para implantar e gerenciar seu FSx para sistemas de arquivos ONTAP e outros recursos da AWS.
* *CloudFormation*: use o código do AWS CloudFormation para executar as ações definidas no console do Workload Factory para modelar, provisionar e gerenciar recursos da AWS e de terceiros da pilha do CloudFormation na sua conta da AWS.
* *Provedor do Terraform NetApp Workload Factory*: use o Terraform para criar e gerenciar fluxos de trabalho de infraestrutura gerados no console do Workload Factory.




== Configurações compatíveis

O Workload Factory oferece suporte aos seguintes mecanismos de banco de dados, versões, sistemas operacionais e modelos de implantação de acordo com as práticas recomendadas da AWS, NetApp ONTAP, Microsoft SQL Server, Oracle e PostgreSQL.

[cols="1,1,1,1"]
|===
| Motor | Versão | Sistema operacional | Modelo de Implantação 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2017 | Qualquer | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Qualquer | FCI, Instância única 


| Microsoft SQL Server | SQL Server 2016, 2019, 2022 | Qualquer | Grupos de disponibilidade sempre ativos 


| Oráculo | 19c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 21c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 19c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 21c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 19c | RHEL, SuSe Linux | Autônomo com ASM (locatário único/múltiplo) 


| Oráculo | 21c | RHEL, SuSe Linux | Autônomo com ASM (locatário único/múltiplo) 


| Oráculo | 19c | RHEL, SuSe Linux | Dataguard 


| Oráculo | 21c | RHEL, SuSe Linux | Dataguard 


| PostgreSQL | PostgreSQL 15 | AMI do Amazon Linux 2023 | HA, instância autônoma 


| PostgreSQL | PostgreSQL 16 | AMI do Amazon Linux 2023 | HA, instância autônoma 
|===


== Serviços integrados da AWS

Os bancos de dados incluem os seguintes serviços integrados da AWS:

* CloudFormation
* Serviço de notificação simples
* CloudWatch
* Gerente de sistemas
* Gestor de segredos




== Regiões

Os bancos de dados são suportados em todas as regiões comerciais onde o FSX for ONTAP é suportado. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Exibir regiões da Amazon compatíveis."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem secreta
* Top nuvem secreta




== Obter ajuda

O Amazon FSX for NetApp ONTAP é uma solução exclusiva da AWS. Para dúvidas ou problemas de suporte técnico associados ao ONTAP sistema de arquivos, infraestrutura ou qualquer solução usando este serviço, use a Central de suporte no Console de Gerenciamento da AWS para abrir um caso de suporte com a AWS. Selecione o serviço "FSX for ONTAP" e a categoria apropriada. Forneça as informações restantes necessárias para criar seu caso de suporte da AWS.

Para perguntas gerais sobre o Workload Factory ou aplicativos e serviços do Workload Factory, consultelink:get-help.html["Obtenha ajuda para o NetApp Workload Factory para bancos de dados"] .
