---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: O NetApp Workload Factory for Databases é um serviço completo de implantação e manutenção de banco de dados com práticas recomendadas integradas para otimização, clonagem fina automática e recursos de monitoramento e resolução. 
---
= Saiba mais sobre o NetApp Workload Factory para bancos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory for Databases é um serviço completo de implantação e manutenção de banco de dados com práticas recomendadas integradas para otimização, clonagem fina automática e recursos de monitoramento e resolução.



== O que é o NetApp Workload Factory para bancos de dados?

NetApp Workload Factory for Databases descobre, avalia, planeja, provisiona e migra dados do Microsoft SQL Server, PostgreSQL e Oracle para implantações do Amazon FSx for NetApp ONTAP (FSx for ONTAP) otimizadas para atender às suas expectativas de desempenho e custo, seguindo as melhores práticas do setor. NetApp Workload Factory for Databases otimiza e gerencia continuamente bancos de dados no FSx for ONTAP.

Para obter mais informações sobre o Workload Factory, consulte olink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Visão geral da Workload Factory"^] .



== Benefícios do Workload Factory para bancos de dados autogerenciados

O Workload Factory oferece as melhores práticas e automação para bancos de dados autogerenciados.



=== Práticas recomendadas

* Conhecimento integrado dos servidores AWS Cloud, Microsoft Windows e SQL e NetApp ONTAP para implantações de servidor SQL em instâncias EC2.
* Implantação otimizada do custo total de propriedade.
* Automação de implantação completa que segue as práticas recomendadas da AWS, Microsoft e ONTAP.
* O modo de implantação de _criação rápida_ ajuda a evitar possíveis armadilhas com configuração manual.




=== Automação com Workload Factory Codebox

O Workload Factory apresenta automação integrada com o _Codebox_.  O Codebox oferece os seguintes benefícios de automação:

* *Geração de trechos de código*: O Workload Factory gera trechos de Infraestrutura como Código (IaC) durante a criação de recursos, permitindo a integração perfeita com fluxos de trabalho de orquestração existentes.
* *Copiloto de infraestrutura como código*: o Codebox é um copiloto de infraestrutura como código (IaC) que ajuda desenvolvedores e DevOps a gerar código para executar qualquer operação suportada pelo Workload Factory.
* *Visualizador de código e catálogo de automação*: O Codebox fornece um visualizador de código para análise rápida da automação e um catálogo de automação para rápida reutilização futura.




=== Recursos do Workload Factory para bancos de dados

O Workload Factory for Databases oferece os seguintes recursos:

* *Estimativa de custos*: avalie a economia potencial de custos com a Savings calculator, que estima e detalha os custos de storage, computação, licenciamento SQL, snapshot e clone para implantações existentes do Microsoft SQL Server e Oracle com Elastic Block Store, FSx for Windows File Server e ambientes locais, em comparação com o FSx for ONTAP.
* *Implantações simples e rápidas*: simplifique e agilize o provisionamento de hosts, bancos de dados e ambientes de teste com práticas recomendadas incorporadas da NetApp, Microsoft e Amazon, que eliminam a complexidade da configuração manual para instâncias do Microsoft SQL Server e PostgreSQL na AWS.
+
** Faça a implantação a partir do console do Workload Factory usando os modos de criação _Rápido_ ou _Avançado_, ou crie, reutilize e personalize modelos CloudFormation da AWS por meio do Codebox para implantações futuras em vários ambientes.
** Crie bancos de dados isolados sob demanda, com configurações de storage e clones de sandbox que podem ser usados para testes, integração, diagnóstico e treinamento, sem afetar dados de produção.


* *Recurso de avaliação de arquitetura bem projetada*: analise continuamente seus ambientes Microsoft SQL Server e Oracle para obter um relatório abrangente com insights, oportunidades e recomendações que ajudarão você a alcançar excelência operacional, segurança, confiabilidade, eficiência de desempenho e otimização de custos com base nas melhores práticas da AWS.
* *Análise de erros*: analise e solucione erros de log com o analisador de IA para obter mensagens de erro detalhadas, etapas de solução de problemas e recomendações para resolver problemas.
* *Gerenciamento centralizado*: gerencie seus recursos do Microsoft SQL Server, Oracle e PostgreSQL no FSx for ONTAP a partir de um único local. No Workload Factory, visualize a infraestrutura conectada, contas AWS, credenciais, sistemas de arquivos FSx for ONTAP conectados, uso de storage incluindo volumes NFS e LUNs iSCSI, status de proteção, desempenho, status de arquitetura adequada e análise de erros.




== Benefícios do Amazon FSX for ONTAP para bancos de dados autogeridos

* *Durabilidade, disponibilidade e confiabilidade*: O FSX for ONTAP oferece vários recursos que aumentam a durabilidade e a disponibilidade de bancos de dados autogeridos hospedados no FSX for ONTAP, como alta disponibilidade com suporte a implantações de zonas de disponibilidade única e múltipla, snapshots com reconhecimento de aplicativos, recuperação de desastres aprimorada usando replicação e backup eficiente.
* *Desempenho e escalabilidade*: O FSX for ONTAP oferece otimização de desempenho com alta taxa de transferência, baixa latência, conexões de rede de alta velocidade e escalabilidade com vários sistemas de arquivos para dimensionar o desempenho agregado necessário para uma carga de trabalho.
* *Gerenciamento e eficiência de dados*: O FSX for ONTAP oferece vários recursos que aprimoram o gerenciamento e a eficiência de dados, como thin clones com uso eficiente de espaço, thin Provisioning, compactação e deduplicação e disposição em camadas de dados acessados com pouca frequência no pool de capacidade.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Saiba mais sobre o FSx para ONTAP para Workload Factory"^] .



== Ferramentas para usar o NetApp Workload Factory

Você pode usar o NetApp Workload Factory com as seguintes ferramentas:

* *Console do Workload Factory*: O console do Workload Factory fornece uma visão visual e holística de seus aplicativos e projetos.
* * NetApp Console*: O NetApp Console oferece uma experiência de interface híbrida para que você possa usar o Workload Factory junto com outros serviços de dados do NetApp .
* *Pergunte-me*: use o assistente de IA Ask me para fazer perguntas e saber mais sobre o Workload Factory sem sair do console do Workload Factory. Acesse Pergunte-me no menu de ajuda do Workload Factory.
* *CloudShell CLI*: O Workload Factory inclui um CloudShell CLI para gerenciar e operar ambientes AWS e NetApp em todas as contas a partir de um único CLI baseado em navegador. Acesse o CloudShell na barra superior do console do Workload Factory.
* *API REST*: Use as APIs REST do Workload Factory para implantar e gerenciar seu FSx para sistemas de arquivos ONTAP e outros recursos da AWS.
* *CloudFormation*: use o código do AWS CloudFormation para executar as ações definidas no console do Workload Factory para modelar, provisionar e gerenciar recursos da AWS e de terceiros da pilha do CloudFormation na sua conta da AWS.
* *Provedor do Terraform NetApp Workload Factory*: use o Terraform para criar e gerenciar fluxos de trabalho de infraestrutura gerados no console do Workload Factory.




== Configurações compatíveis

Você pode usar o Workload Factory com os seguintes mecanismos de banco de dados, versões, sistemas operacionais e modelos de implantação, seguindo as melhores práticas da AWS, NetApp ONTAP, Microsoft SQL Server, Oracle e PostgreSQL.

[cols="1,1,1,1"]
|===
| Motor | Versão | Sistema operacional | Modelo de Implantação 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, Independente 


| Microsoft SQL Server | SQL Server 2017 | Qualquer | FCI, Independente 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Qualquer | FCI, Independente 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Qualquer | Grupo de disponibilidade Always On 


| Oráculo | 19c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 21c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 19c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 21c | RHEL, SuSe Linux | Autônomo (inquilino único/múltiplo) 


| Oráculo | 19c | RHEL, SuSe Linux | Autônomo com ASM (locatário único/múltiplo) 


| Oráculo | 21c | RHEL, SuSe Linux | Autônomo com ASM (locatário único/múltiplo) 


| Oráculo | 19c, 21c | RHEL, SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | AMI do Amazon Linux 2023 | HA, instância autônoma 


| PostgreSQL | PostgreSQL 16 | AMI do Amazon Linux 2023 | HA, instância autônoma 
|===


== Serviços integrados da AWS

Os bancos de dados incluem os seguintes serviços integrados da AWS:

* CloudFormation
* Serviço de notificação simples
* CloudWatch
* Gerente de sistemas
* Gestor de segredos




== Regiões

Os bancos de dados são suportados em todas as regiões comerciais onde o FSX for ONTAP é suportado. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Exibir regiões da Amazon compatíveis."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem secreta
* Top nuvem secreta




== Obter ajuda

O Amazon FSX for NetApp ONTAP é uma solução exclusiva da AWS. Para dúvidas ou problemas de suporte técnico associados ao ONTAP sistema de arquivos, infraestrutura ou qualquer solução usando este serviço, use a Central de suporte no Console de Gerenciamento da AWS para abrir um caso de suporte com a AWS. Selecione o serviço "FSX for ONTAP" e a categoria apropriada. Forneça as informações restantes necessárias para criar seu caso de suporte da AWS.

Para perguntas gerais sobre o Workload Factory ou aplicativos e serviços do Workload Factory, consultelink:get-help.html["Obtenha ajuda para o NetApp Workload Factory para bancos de dados"] .
