---
sidebar: sidebar 
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs 
summary: Rastreie trabalhos de banco de dados e monitore bancos de dados no Workload Factory para bancos de dados. 
---
= Monitorar bancos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Acompanhe trabalhos de banco de dados e monitore bancos de dados com o Workload Factory para bancos de dados.

.Sobre esta tarefa
Os bancos de dados fornecem monitoramento de tarefas para que você possa acompanhar o progresso da tarefa e diagnosticar e solucionar problemas caso ocorra alguma falha. Além disso, filtra por tipo e estado, a função de pesquisa e a opção de transferir a ajuda da tabela de trabalhos com navegação e relatórios de trabalhos de base de dados.

A monitorização de trabalhos suporta até três níveis de monitorização, dependendo do trabalho. Por exemplo, para a criação de novos clones de banco de dados e sandbox, o monitoramento de tarefas rastreia trabalhos pai e subtarefas.

Níveis de monitorização do trabalho::
+
--
* Nível 1 (trabalho pai): Controla o trabalho de implantação do host.
* Nível 2 (subtarefa): Controla os sub-trabalhos relacionados com a tarefa principal de implementação do host.
* Nível 3 (tarefa): Lista a sequência de ações realizadas em cada recurso.


--
Estado do trabalho:: O recurso de monitoramento de tarefas rastreia tarefas _em andamento_, _completed_ e _failed_ diárias, semanais, quinzenais e mensais.
Retenção de eventos de trabalho:: Os eventos de monitorização de trabalhos são mantidos na interface do utilizador durante 30 dias.




== Monitorizar trabalhos

.Passos
. Inicie sessão no link:https://console.workloads.netapp.com["Console de fábrica da carga de trabalho"^].
. No bloco bancos de dados, selecione *ir para Inventário de bancos de dados*.
. Em bancos de dados, selecione a guia *Monitoramento de tarefas*.
. No separador monitorização de trabalhos, utilize os filtros ou procure para restringir os resultados dos trabalhos. Também pode transferir um relatório de trabalhos.
. Clique no menu três pontos da tarefa e clique em *vá para o CloudFormation* para exibir o log de tarefas no console do AWS CloudFormation.

