---
sidebar: sidebar 
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs 
summary: Rastreie trabalhos de banco de dados e monitore bancos de dados dentro da fábrica de carga de trabalho para bancos de dados. 
---
= Monitorar trabalhos de banco de dados na fábrica de carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Rastreie trabalhos de banco de dados e monitore bancos de dados dentro da fábrica de carga de trabalho para bancos de dados.

.Sobre esta tarefa
Os bancos de dados fornecem monitoramento de tarefas para que você possa acompanhar o progresso da tarefa e diagnosticar e solucionar problemas caso ocorra alguma falha. Pode filtrar trabalhos por tipo e estado, localizar trabalhos utilizando a função de pesquisa e transferir a tabela trabalhos.

A monitorização de trabalhos suporta até três níveis de monitorização, dependendo do trabalho. Por exemplo, para a criação de novos clones de banco de dados e sandbox, o monitoramento de tarefas rastreia trabalhos pai e subtarefas.

Níveis de monitorização do trabalho::
+
--
* Nível 1 (trabalho pai): Controla o trabalho de implantação do host.
* Nível 2 (subtarefa): Controla os sub-trabalhos relacionados com a tarefa principal de implementação do host.
* Nível 3 (tarefa): Lista a sequência de ações realizadas em cada recurso.


--
Estado do trabalho:: O recurso de monitoramento de tarefa rastreia _em andamento_, _completed_, _completed with issues_ e _failed_ trabalhos diariamente, semanalmente, quinzenalmente e mensalmente.
Retenção de eventos de trabalho:: Os eventos de monitorização de trabalhos são mantidos na interface do utilizador durante 30 dias.




== Monitorizar trabalhos

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Em bancos de dados, selecione a guia *Monitoramento de tarefas*.
. No separador monitorização de trabalhos, utilize os filtros ou procure para restringir os resultados dos trabalhos. Também pode transferir um relatório de trabalhos.
. Clique no menu de três pontos da tarefa e clique em *vá para o CloudFormation* para exibir o log de tarefas no console do AWS CloudFormation.

