---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: O Workload Factory for Databases analisa as configurações do Microsoft SQL Server e do Oracle regularmente para determinar se há algum problema. 
---
= Análise de configuração para ambientes de banco de dados no Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O Workload Factory for Databases analisa as configurações do banco de dados regularmente para determinar se há algum problema com as implantações do Microsoft SQL Server e do Oracle no Amazon FSx for NetApp ONTAP .  Quando problemas são encontrados, o Workload Factory mostra quais são os problemas e explica o que precisa ser alterado para garantir que as configurações do seu banco de dados atinjam o desempenho máximo, a eficiência de custos e a conformidade com as práticas recomendadas.

Os principais recursos incluem:

* Análise de configuração diária
* Validações automáticas de melhores práticas
* Recomendações para o dimensionamento correto
* Observabilidade proativa
* Insights para ação
* Consultor do AWS Well-Architected Framework




== Status bem arquitetado

No console do Workload Factory, no nível do sistema de arquivos, o status bem arquitetado é listado para todos os sistemas de arquivos FSx para ONTAP . Os status bem arquitetados são categorizados como "problemas", "não analisados" ou "bem arquitetados". Selecionar o status bem-arquitetado redireciona você para a guia de status bem-arquitetado no sistema de arquivos, onde você pode encontrar a pontuação bem-arquitetada, categorias de configuração e todas as configurações do sistema de arquivos.



== Pontuação bem arquitetada

A pontuação inclui todas as configurações analisadas atualmente e aparece como uma porcentagem. Uma pontuação de 25% significa que 25% das configurações do sistema de arquivos são bem arquitetadas.



== Categorias de configuração

As configurações do sistema de arquivos são organizadas em categorias alinhadas com os cinco pilares a seguir do AWS Well-Architected Framework.

* _Confiabilidade_: Garante que as cargas de trabalho executem suas funções pretendidas de forma correta e consistente, mesmo quando há interrupções. Um exemplo de configuração é o FSX for ONTAP backups.
* _Security_: Enfatiza a proteção de dados, sistemas e ativos por meio de avaliações de risco e estratégias de mitigação.
* _Excelência operacional_: Concentra-se em fornecer a arquitetura e o valor de negócios mais ideais.
* _Otimização de custos_: Visa fornecer valor de negócio ao mesmo tempo que minimiza custos.
* _Eficiência de desempenho_: Se concentra em usar recursos de forma eficiente para atender aos requisitos do sistema e manter o desempenho ideal à medida que as demandas mudam.




== Escopo de análise

O escopo da otimização é diferente dependendo de qual componente está sendo avaliado. Por exemplo, a otimização de storage ocorre no nível de instância SQL, enquanto a otimização de computação ocorre no nível de host.



== Requisitos de análise

Para uma análise completa do ambiente de banco de dados, os recursos devem estar registrados e online.

link:register-instance.html["Aprenda como registrar recursos."]

.O que vem a seguir
link:optimize-configurations.html["Implementar configurações de banco de dados bem arquitetadas"]
