---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: O Workload Factory for Databases analisa as configurações do Microsoft SQL Server e do Oracle regularmente para determinar se há algum problema. 
---
= Análise de configuração para ambientes de banco de dados no Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O Workload Factory for Databases analisa as configurações do banco de dados regularmente para determinar se há algum problema com as implantações do Microsoft SQL Server e do Oracle no Amazon FSx for NetApp ONTAP .  Quando problemas são encontrados, o Workload Factory mostra quais são os problemas e explica o que precisa ser alterado para garantir que as configurações do seu banco de dados atinjam o desempenho máximo, a eficiência de custos e a conformidade com as práticas recomendadas.

Os principais recursos incluem:

* Análise de configuração diária
* Validações automáticas de melhores práticas
* Recomendações para o dimensionamento correto
* Observabilidade proativa
* Insights para ação
* Consultor do AWS Well-Architected Framework




== Componentes da análise de configuração

A análise de configuração inclui os seguintes componentes:

Status bem arquitetado:: O status de "bem arquitetado" refere-se à saúde geral das configurações do seu banco de dados; as configurações são categorizadas como "otimizadas", "não otimizadas" ou "com recursos em excesso". O status de arquitetura adequada de uma configuração é referenciado a partir de uma instância do Microsoft SQL Server ou de um banco de dados Oracle no console do Workload Factory.
Pontuação bem arquitetada:: A pontuação inclui todas as configurações analisadas até o momento e é apresentada em porcentagem. Uma pontuação de 25% significa que 25% das suas implementações de banco de dados estão bem arquitetadas. A pontuação de boa arquitetura é referenciada na tela *Bem arquitetado* e em uma instância do Microsoft SQL Server ou banco de dados Oracle no console do Workload Factory.
Categorias de configuração:: As configurações estão organizadas nas seguintes categorias: armazenamento, computação, aplicação, resiliência e clonagem. Cada categoria inclui avaliações de configuração específicas que são analisadas regularmente. As categorias de configuração são referenciadas na tela *Bem arquitetado* e em uma instância do Microsoft SQL Server ou banco de dados Oracle no console do Workload Factory.




== Escopo de análise

O escopo da otimização é diferente dependendo de qual componente está sendo avaliado. Por exemplo, a otimização de storage ocorre no nível de instância SQL, enquanto a otimização de computação ocorre no nível de host.



== Requisitos de análise

Para uma análise completa do ambiente de banco de dados, os recursos devem estar registrados e online.

link:register-instance.html["Aprenda como registrar recursos."]

.O que vem a seguir
link:optimize-configurations.html["Implementar configurações de banco de dados bem arquitetadas"]
