---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: A fábrica de carga de trabalho para bancos de dados verifica as configurações do Microsoft SQL Server, fornecendo insights e recomendações para ajudar você a atingir a excelência operacional. 
---
= Implementar configurações de banco de dados bem arquitetadas na fábrica de carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Usando insights e recomendações de análise de configuração, aproveite o Workload Factory para implementar práticas recomendadas para suas configurações de banco de dados com Microsoft SQL Server e Oracle.  Você pode facilmente revisar o status bem arquitetado, aprender sobre problemas com configurações de banco de dados e tomar medidas para melhorar quaisquer configurações que não estejam otimizadas para confiabilidade, segurança, eficiência, desempenho e custo.

Você também pode descartar a análise de configurações específicas que não se aplicam ao seu ambiente para evitar alertas desnecessários e resultados de otimização imprecisos.

link:optimize-overview.html["Aprenda sobre a análise de configuração e o status bem arquitetado na fábrica de carga de trabalho."]



== Sobre esta tarefa

A Workload Factory analisa as configurações do banco de dados diariamente. A análise diária fornece o status bem arquitetado, insights e recomendações com opções para corrigir automaticamente problemas de configuração para que suas configurações atendam às melhores práticas.

Você tem opções para revisar as recomendações para problemas de configuração e corrigir esses problemas no inventário de bancos de dados no console do workload factory.

.O que é analisado
A fábrica de carga de trabalho analisa o status bem arquitetado das seguintes configurações:

Para instâncias do Microsoft SQL Server:

* Dimensionamento do armazenamento: Inclui camada de armazenamento, espaço livre do sistema de arquivos, tamanho da unidade de Registro e tamanho da unidade TempDB
* Layout de armazenamento: Inclui posicionamento de arquivos de dados do usuário, posicionamento de arquivos de log e posicionamento TempDB
* Configuração de armazenamento: inclui gerenciamento de capacidade, provisionamento fino, política de camadas, instantâneos, status do Microsoft Multipath I/O (MPIO) e configuração de tempo limite do MPIO
* Computação: inclui redimensionamento, patches do sistema operacional e configurações do adaptador de rede, como dimensionamento do lado do recebimento (RSS), descarregamento de TCP e alinhamento de MTU
* Aplicações: Inclui licenças Microsoft SQL Server, Microsoft SQL Server patch e configurações MAXDOP
* Resiliência: inclui snapshots locais, FSx para backups ONTAP , replicação entre regiões (CRR) e alta disponibilidade do Microsoft SQL.
* Clones: inclui opções para atualizar e excluir clones (sandboxes) que foram criados dentro ou fora da fábrica de carga de trabalho e têm mais de 60 dias


Para bancos de dados Oracle:

* Configuração de armazenamento: inclui gerenciamento de capacidade, provisionamento fino, política de níveis, instantâneos e eficiências de armazenamento




== Antes de começar

* Você deve ter link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenciais da conta AWS e permissões de leitura/gravação"^] para analisar as configurações do seu banco de dados.
* Para avaliar o armazenamento de uma instância do Microsoft SQL Server ou banco de dados Oracle, o recurso deve ser registrado no workload factory e o tipo de armazenamento deve ser FSx para ONTAP.link:register-instance.html["Aprenda como registrar recursos."]
* Certifique-se de rever cada recomendação cuidadosamente antes de selecionar para corrigir uma configuração ou configuração. Para as configurações RSS e MAXDOP, sugerimos que você teste as configurações recomendadas para determinar melhorias de desempenho antes de fazer alterações no seu ambiente de produção.



NOTE: O processo de remediação pode causar tempos de inatividade da instância ou interrupções de serviço. Certifique-se de revisar a recomendação cuidadosamente antes de decidir corrigir uma configuração.



== Corrigir um problema de configuração

Corrija problemas de configuração para ambientes SQL Server ou Oracle em execução no FSx para armazenamento ONTAP .


NOTE: O processo de correção pode causar tempos de inatividade da instância ou interrupções de serviço.  Certifique-se de revisar a recomendação cuidadosamente antes de decidir corrigir um problema de configuração.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Na guia *Inventário*, selecione a guia *instâncias*.
. Selecione *Corrigir problemas* para visualizar os problemas de configuração da instância.
. Na página de status Bem arquitetado da instância, revise as descobertas da análise.
+
Você pode filtrar problemas de configuração por categorias, subcategorias, status, gravidade e tags.

+
Você também pode baixar um relatório das descobertas selecionando *Exportar PDF*.

. Selecione a seta suspensa para exibir a recomendação para qualquer configuração. As recomendações incluem práticas recomendadas, possíveis armadilhas de configurações não otimizadas e considerações importantes. Certifique-se de rever a recomendação com cuidado.
. Selecione *Visualizar e corrigir* problemas de configuração quando a opção estiver disponível.
+
*Selecionar tudo* é o padrão, mas você pode selecionar recursos específicos para corrigir.

+
.. Para todas as configurações, exceto a limpeza de clones, revise os detalhes da recomendação para saber o que acontecerá se você decidir corrigir o problema. Algumas operações de remediação podem causar inatividade da instância ou interrupções do serviço.
.. Para limpeza de clones, selecione bancos de dados clonados (caixas de areia) para atualizar ou excluir.
+
*** Atualizar um clone sincroniza-o com seu banco de dados de origem. A atualização está disponível apenas para clones criados na fábrica de workloads.
*** A exclusão de um clone remove-o permanentemente, libera espaço de armazenamento e reduz custos. Você pode excluir clones criados dentro e fora do workload de fábrica.




. Selecione *continuar* para corrigir o problema de configuração.


.Resultado
A fábrica de carga de trabalho começa a corrigir o(s) problema(s). Selecione o separador *monitorização de trabalhos* para ver o estado da operação.



== Adiar ou ignorar a análise das configurações do banco de dados

Adie ou ignore a análise de configurações de banco de dados específicas que não se aplicam ao ambiente de banco de dados para evitar alertas desnecessários e resultados de otimização imprecisos. Você pode reativar uma análise de configuração adiada ou descartada a qualquer momento.

Os requisitos do aplicativo para configurações de banco de dados variam. A fábrica de carga de trabalho oferece duas opções para ignorar a análise de configurações específicas de banco de dados, para que você possa monitorar apenas problemas relevantes e obter uma visão precisa da integridade das configurações relevantes. Quando uma análise de configuração específica é adiada ou descartada, a configuração não é incluída na pontuação total de otimização.

Você pode adiar, descartar e reativar a análise de configuração no nível de configuração e na instância do SQL Server ou no nível do banco de dados Oracle.

* *Adiar por 30 dias*: Adiar a análise interromperá a análise por 30 dias. Após 30 dias, a análise será reiniciada automaticamente.
* *Dismiss*: Rejeitar a análise adia a análise indefinidamente. Você pode reiniciar a análise, se necessário.


As instruções a seguir descrevem como adiar, descartar ou reativar uma análise no nível de configuração.  Para concluir as seguintes tarefas para instâncias específicas do SQL Server ou bancos de dados Oracle, comece na guia *Painel*.

[role="tabbed-block"]
====
.Adiar
--
Adiar para parar uma análise de configuração por 30 dias. Após 30 dias, a análise será reiniciada automaticamente.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Na guia *Inventário*, role para baixo até a configuração para adiar, selecione o menu de três pontos e, em seguida, selecione *adiar por 30 dias*.
. Selecione *continuar*.


.Resultado
A análise de configuração pára por 30 dias.

--
.Dispensar
--
Ignorar para interromper uma análise de configuração indefinidamente. Você pode reiniciar a análise quando necessário.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Na guia *Inventory*, role para baixo até a configuração a ser descartada, selecione o menu de três pontos e selecione *Dismiss*.
. Selecione *continuar*.


.Resultado
A análise de configuração pára.

--
.Reativar
--
Reative uma análise de configuração adiada ou descartada a qualquer momento.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Na guia *Inventário*, role para baixo até a configuração para reativar, selecione o menu de três pontos e, em seguida, selecione *reativar*.
. Selecione *continuar*.


.Resultado
A análise de configuração é reativada e ocorre diariamente a avançar.

--
====