---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: A fábrica de workloads do BlueXP  para bancos de dados verifica as configurações de storage dos Microsoft SQL Servers, fornecendo insights e recomendações para ajudá-lo a alcançar a excelência operacional. 
---
= Otimize as configurações para implantações do Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A fábrica de carga de trabalho do BlueXP  para bancos de dados verifica e avalia continuamente as configurações de implantação do Microsoft SQL Server em execução no Amazon FSX for NetApp ONTAP. As avaliações fornecem insights, recomendações e otimizações para que você alcance a excelência operacional.

.Sobre esta tarefa
A avaliação é executada automaticamente e continuamente uma vez por dia para instâncias do Microsoft SQL Server com o armazenamento do FSX for ONTAP gerenciado na fábrica de cargas de trabalho. Os relatórios de avaliação estão disponíveis no painel de otimização somente se um trabalho agendado diário tiver sido executado após a implantação ou após o gerenciamento de uma instância.

A fábrica de carga de trabalho fornece recomendações detalhadas para otimizar configurações com base nas práticas recomendadas do FSX for ONTAP.

O que é digitalizado:: A fábrica de carga de trabalho avalia o status de otimização das seguintes configurações para instâncias do Microsoft SQL Server:
+
--
* Dimensionamento do armazenamento: Inclui camada de armazenamento, espaço livre do sistema de arquivos, tamanho da unidade de Registro e tamanho da unidade TempDB
* Layout de armazenamento: Inclui posicionamento de arquivos de dados do usuário, posicionamento de arquivos de log e posicionamento TempDB
* Configuração de storage: Inclui gerenciamento de capacidade, thin Provisioning, política de disposição em categorias, snapshots, status, política e sessões de e/S de vários caminhos e muito mais
* Computação: Inclui redimensionamento


--


.Antes de começar
* Você precisa ter credenciais com permissões de leitura ou automação.
* Para avaliar o armazenamento de uma instância do Microsoft SQL Server, a instância deve ser gerenciada de fábrica de carga de trabalho e o tipo de armazenamento deve ser o FSX for ONTAP.
* Certifique-se de rever cada recomendação cuidadosamente antes de selecionar para otimizar uma configuração ou configuração.


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para Inventário de bancos de dados*.
. Em bancos de dados, selecione a guia *Inventário*.
. Clique na seta suspensa para expandir a linha do host para exibir suas instâncias gerenciadas.
+
O host se expande e as instâncias do host aparecem.

. Selecione o menu de três pontos da instância para digitalizar e, em seguida, selecione *Otimize*.
. Na página Otimize instance (otimizar instância) do host, revise as descobertas da avaliação de armazenamento.
+
Os filtros estão disponíveis para classificar por categorias, sub-categorias, status, gravidade e tags.

+
Se necessário, você pode baixar um relatório das descobertas selecionando *Exportar PDF*.

. Selecione a seta suspensa para exibir a recomendação para qualquer configuração. Certifique-se de rever a recomendação com cuidado.
+
A recomendação explica as práticas recomendadas e possíveis armadilhas de configurações não otimizadas.

. Selecione para *otimizar* configurações não otimizadas.
. Revise o resumo da otimização e os itens de ação que aparecem na caixa de diálogo de otimização para saber o que acontecerá se você optar por otimizar. Algumas operações de otimização podem causar tempos de inatividade de instâncias ou interrupções de serviço.
. Selecione *continuar* para otimizar a configuração.


.Resultado
O processo de otimização é iniciado. Selecione o separador *monitorização de trabalhos* para ver o estado da operação.
