---
sidebar: sidebar 
permalink: refresh-clone.html 
keywords: refresh clone, sync, update, database, Microsoft SQL 
summary: Atualize um clone de banco de dados no NetApp Workload Factory for Databases para que ele seja equivalente ao banco de dados de origem no momento atual ou em um momento anterior. 
---
= Atualizar um clone de banco de dados no NetApp Workload Factory for Databases
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Atualize um clone de banco de dados (sandbox) no NetApp Workload Factory for Databases para que ele seja equivalente ao banco de dados de origem no momento atual ou em um momento anterior.

.Sobre esta tarefa
Atualizar um clone atualiza o clone para o banco de dados de origem no momento atual ou para um instantâneo do banco de dados de origem obtido em um ponto anterior no tempo. Quaisquer alterações feitas no clone da sandbox serão excluídas.

.Antes de começar
Uma atualização só é possível quando o banco de dados de origem está ativo.

Para atualizar um clone de banco de dados de um snapshot, o banco de dados de origem deve ter pelo menos um snapshot para a operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. No menu Bancos de dados, selecione *Sandboxes*.
. Em Sandboxes, selecione o menu de ação do clone do sandbox que você deseja atualizar.
. Selecione *Atualizar*.
. Na caixa de diálogo Atualizar, selecione uma das seguintes opções:
+
.. *Atualizar para a hora atual*
.. *Atualizar para ponto no tempo*
+
Para esta opção, selecione o instantâneo da base de dados no menu pendente para o qual pretende atualizar.



. Clique em *Atualizar*.

