---
sidebar: sidebar 
permalink: register-instance.html 
keywords: manage, register, Microsoft SQL Server instance, Oracle database, manage database, manage instance 
summary: Registre recursos para que você possa monitorar o status dos recursos, a utilização dos recursos, a proteção e o desempenho do armazenamento no NetApp Workload Factory for Databases. 
---
= Registrar recursos no NetApp Workload Factory para bancos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Registre instâncias para Microsoft SQL Server e bancos de dados para Oracle para que você possa monitorar o status da instância e do banco de dados, a utilização de recursos, a proteção e o desempenho do armazenamento no NetApp Workload Factory for Databases.

O registro só é possível para mecanismos de bancos de dados executados no FSx para armazenamento do sistema de arquivos ONTAP .



== Sobre a tarefa

O registro de uma instância (SQL Server) ou banco de dados (Oracle) inclui duas etapas: autenticação e preparação.  A preparação envolve garantir que todos os módulos AWS, NetApp e PowerShell estejam instalados na instância.

Você pode autenticar usando credenciais do SQL Server ou com credenciais do Windows.


NOTE: O Workload Factory oferece suporte apenas ao registro e gerenciamento de instâncias do Microsoft SQL Server e do banco de dados Oracle.  Dependendo das credenciais da conta da AWS selecionadas no Workload Factory, os hosts PostgreSQL podem aparecer no Inventário.  Atualmente, o Workload Factory oferece suporte a instâncias não registradas do PostgreSQL executadas apenas em sistemas operacionais Amazon Linux.



== Antes de começar

Considere o seguinte antes de registrar uma instância:

O host da instância ou banco de dados deve aparecer no Inventário. Para que os hosts apareçam no inventário,link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["você deve adicionar credenciais de conta AWS e permissões de modo _somente leitura_ ou _leitura/gravação_"^] .



=== Registrando uma instância em uma rede privada

Para registrar uma instância (SQL Server) ou banco de dados (Oracle) em uma rede privada sem conectividade externa, os seguintes endpoints precisam estar disponíveis na VPC com associação às sub-redes onde os servidores SQL estão presentes.  Certifique-se de que os pontos de extremidade da interface permitam a porta 443 no Grupo de Segurança anexado.

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`
+
Se você usar um servidor proxy para todas as conexões de saída de instâncias EC2, deverá permitir o acesso aos seguintes domínios para que as operações de gerenciamento funcionem:

* ``.microsoft.com``(Servidor SQL)
* ``.powershellgallery.com``(Servidor SQL)
* ``.aws.amazon.com``
* ``.amazonaws.com``




== Registrar uma instância do SQL Server

O registro de uma instância inclui autenticação e preparação da instância.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. No menu Bancos de dados, selecione *Inventário*.
. No Inventário, selecione *Microsoft SQL Server* como o tipo de mecanismo.
. Selecione a aba *Instâncias*.
. Selecione para registrar uma única instância ou múltiplas instâncias.
+
.. Registro de instância única: navegue até a instância a ser gerenciada e selecione *Registrar instância*.
.. Registro de múltiplas instâncias: Selecione o botão *Registrar múltiplas instâncias*.
+
Há duas opções disponíveis para registrar múltiplas instâncias. Em ambos os casos, as instâncias devem compartilhar o mesmo status de autenticação (não autenticada ou autenticada).

+
*** Instâncias não autenticadas: selecione várias instâncias não autenticadas para registrar. Essas instâncias devem compartilhar as mesmas credenciais de autenticação e as credenciais do FSx para ONTAP. Selecione *Aplicar* e depois *Avançar*.
*** Instâncias autenticadas: selecione várias instâncias autenticadas para registrar e selecione *Avançar*.




. Na etapa 2 da página Registrar instâncias, selecione o modo de autenticação da instância, insira as seguintes informações e selecione *Avançar*. Se as instâncias já estiverem autenticadas, selecione *Avançar*.
+
** *Autenticação do SQL Server*: insira o nome de usuário e a senha do SQL Server, e o nome de usuário e a senha do sistema de arquivos FSx para ONTAP.
** *Autenticação do Windows*: Digite o nome de usuário e a senha do Windows, e o nome de usuário e a senha do sistema de arquivos FSx para ONTAP.


. Na etapa 3, prepare a instância certificando-se de que ela atende aos pré-requisitos necessários. Se todos os módulos necessários estiverem instalados e os pré-requisitos forem atendidos, selecione *Avançar* para registrar a instância. Se precisar tomar alguma providência, siga estas etapas.
+
.. Se ausente, selecione a fábrica de carga de trabalho para *Instalar os módulos AWS e NetApp PowerShell ausentes*.
.. Se estiver ausente, selecione a fábrica de carga de trabalho para *Instalar o PowerShell 7 ausente*. A instalação do módulo 7 do PowerShell ausente requer uma reinicialização do sistema.
.. Revise a lista de pré-requisitos para os seguintes recursos.  Certifique-se de atender a todos os pré-requisitos por capacidade para registrar a instância.
+
*** *Revise problemas e recomendações bem arquitetados*
*** *Corrija problemas bem arquitetados*
*** *Criar banco de dados*
*** *Criar cópias do banco de dados (sandbox)*
+
A conclusão dos pré-requisitos inclui a atualização das permissões da política do AWS IAM, das permissões do perfil da instância do EC2 IAM, das permissões do SQL Server e dos módulos do PowerShell.



.. Quando os pré-requisitos estiverem concluídos e as verificações estiverem *Prontas*, você pode selecionar *Registrar* a instância.




.Resultado
O registro da instância é iniciado.  Selecione a aba *Monitoramento de tarefas* para acompanhar o progresso.



== Registrar um banco de dados Oracle

O registro de um banco de dados inclui autenticação e preparação da instância.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. No menu Bancos de dados, selecione *Inventário*.
. No Inventário, selecione *Oracle* como o mecanismo de banco de dados.
. Selecione a aba *Bancos de dados*.
. Selecione para registrar um único banco de dados ou vários bancos de dados.
+
.. Registro de banco de dados único: navegue até o banco de dados a ser gerenciado e selecione *Registrar banco de dados*.
.. Registro de vários bancos de dados: Selecione o botão *Registrar vários bancos de dados*.
+
Duas opções estão disponíveis para registrar vários bancos de dados.  Em ambos os casos, os bancos de dados devem compartilhar o mesmo status de autenticação (não autenticado ou autenticado).

+
*** Bancos de dados não autenticados: selecione vários bancos de dados não autenticados para registrar.  Esses bancos de dados devem compartilhar as mesmas credenciais de autenticação e credenciais do FSx para ONTAP .  Selecione *Aplicar* e depois *Avançar*.
*** Bancos de dados autenticados: selecione vários bancos de dados autenticados para registrar e selecione *Avançar*.




. Na etapa 2 da página Registrar bancos de dados, selecione o modo de autenticação do banco de dados, insira os seguintes detalhes e selecione *Avançar*.  Se os bancos de dados já estiverem autenticados, selecione *Avançar*.
+
** *Autenticação de usuário Oracle*: Digite o nome de usuário e a senha do Oracle, e o nome de usuário e a senha do sistema de arquivos FSx para ONTAP .
** *Autenticação de usuário Oracle ASM*: Opcional.  Se o banco de dados Oracle usar o Automatic Storage Management (ASM), insira o nome de usuário e a senha do Oracle ASM (grade).


. Na etapa 3, prepare o banco de dados certificando-se de que ele atende aos pré-requisitos necessários.  Se todos os módulos necessários estiverem instalados e os pré-requisitos forem atendidos, selecione *Avançar* para registrar o banco de dados.  Se precisar tomar alguma atitude, siga estes passos.
+
.. Revise a lista de pré-requisitos para o seguinte recurso.  Todos os pré-requisitos para um único recurso devem ser atendidos para registrar o banco de dados.
+
*** *Revise problemas e recomendações bem arquitetados*


.. Conclua os seguintes pré-requisitos:
+
*** *Permissões de política do AWS IAM*: copie e atualize as permissões da AWS no console da AWS.
*** *Permissões de perfil de instância do EC2 IAM*: copie e atualize as permissões de perfil de instância do EC2 IAM na instância do Amazon EC2 no console da AWS.
*** *Módulos de implantação*: Se necessário, selecione para instalar módulos dependentes que incluem a interface de linha de comando da AWS (AWS CLI), jq (processador JSON de linha de comando) e Python 3.12, se a versão 3.6 ou superior ainda não estiver instalada.  O Workload Factory instala automaticamente esses módulos como parte do processo de registro.
*** *Permissões do usuário Oracle*: Se necessário, atualize as permissões do usuário Oracle.


.. Quando os pré-requisitos estiverem concluídos e as verificações estiverem *Prontas*, você pode selecionar *Registrar* o banco de dados.




.Resultado
O registro do banco de dados é iniciado.  Selecione a aba *Monitoramento de tarefas* para acompanhar o progresso.

.O que vem a seguir
Após o registro do recurso, você pode executar as seguintes tarefas.

* Ver bancos de dados do inventário
* link:create-database.html["Crie um banco de dados"]
* link:create-sandbox-clone.html["Criar um clone de banco de dados (sandbox)"]
* link:optimize-configurations.html["Implementar configurações de banco de dados bem arquitetadas"]

