---
sidebar: sidebar 
permalink: split-clone.html 
keywords: split, clone, source, new database 
summary: Divida um clone de banco de dados do banco de dados de origem para criar um novo banco de dados no NetApp Workload Factory for Databases. 
---
= Dividir um clone de banco de dados do banco de dados de origem
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
No NetApp Workload Factory for Databases, a divisão de um clone de banco de dados de seu banco de dados de origem cria um novo banco de dados que consumirá uma certa quantidade de capacidade de armazenamento.  O clone é excluído quando a divisão é concluída e o novo banco de dados aparece no Inventário.

.Antes de começar
Considere a quantidade de capacidade de armazenamento necessária para o novo banco de dados. Se necessário, link:https://docs.netapp.com/us-en/workload-fsx-ontap/increase-file-system-capacity.html["aumentar a capacidade do sistema de arquivos"^] para o sistema de arquivos FSX for ONTAP antes de começar.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. No menu Bancos de dados, selecione *Sandboxes*.
. Em Sandboxes, selecione o menu de ação do clone do banco de dados que você deseja dividir.
. Selecione *Split*.
. Na caixa de diálogo Dividir, selecione *Dividir*.

