---
sidebar: sidebar 
permalink: view-databases.html 
keywords:  
summary: Para obter um resumo dos recursos do banco de dados na fábrica de carga de trabalho, visualize todos os bancos de dados no inventário de bancos de dados. Você também pode visualizar os bancos de dados por instância registrada. 
---
= Exibir bancos de dados na fábrica de carga de trabalho para bancos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para obter um resumo dos recursos do banco de dados na fábrica de carga de trabalho, visualize todos os bancos de dados no inventário de bancos de dados. Você também pode visualizar os bancos de dados por instância registrada.

.Antes de começar
* Instâncias que contêm recursos de banco de dados devem ter FSx para armazenamento do sistema de arquivos ONTAP.
* Você deve registrar instâncias no workload factory para visualizar bancos de dados. Saiba como link:register-instance.html["registrar uma instância"] .


.Passos
[role="tabbed-block"]
====
.Exibir bancos de dados para uma única instância
--
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Em bancos de dados, selecione a guia *Inventário*.
. Clique no menu de três pontos da instância e selecione *Exibir bancos de dados*.


Os bancos de dados são exibidos para a instância única na guia Bancos de dados.

--
.Exibir bancos de dados para todas as instâncias
--
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco bancos de dados, selecione *ir para inventário de bancos de dados*.
. Em bancos de dados, selecione a guia *Inventário*.
. Selecione a aba *Bancos de dados*.
+
Os bancos de dados são exibidos para todas as instâncias registradas.



--
====